# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

log_Gaussian <- function(y, pars) {
    .Call(`_hmmcr_log_Gaussian`, y, pars)
}

mcmc_routine <- function(par_index, par_init, par_prior, par_unique, y, X, Z, S, id, model, nr_states, groups, steps, burnin) {
    .Call(`_hmmcr_mcmc_routine`, par_index, par_init, par_prior, par_unique, y, X, Z, S, id, model, nr_states, groups, steps, burnin)
}

